# Generated by Django 4.1 on 2023-06-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingreservation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='parkingreservation',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='parkingreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
